"""Added status column to Case model

Revision ID: e401a55438ac
Revises: 
Create Date: 2024-03-30 19:55:57.791342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e401a55438ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cases')
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.create_table('cases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dtc', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stopreason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unit_details', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('firmware_version', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('severity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('applicability', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cases_pkey')
    )
    # ### end Alembic commands ###
